### ISSUE TITLE
Occasionally, my Arduino Nano 33 BLE is not detected by the gRPC equivalent of `board list watch` after an upload

### ISSUE THREAD

**Issue by kittaakos** [arduino/serial-discovery#51]
### Describe the problem

From time to time, [IDE2](https://github.com/arduino/arduino-ide) cannot detect the Arduino Nano 33 BLE board after uploading on macOS. I cannot consistently reproduce the defect but what I see is the following error as an `INFO` from the daemon process:

```
2022-12-12T08:35:49.545Z daemon INFO INFO[0103] from discovery builtin:serial-discovery received message type: start_sync, message: Error enumerating serial ports: Error while enumerating serial ports: Error extracting port info from device: Property not found: IOCalloutDevice 
```

The relevant part when the upload is done:

```
2022-12-12T08:35:48.760Z daemon INFO 258 |  RESP: {
258 |    "out_stream": "d3JpdGUoYWRkcj0weDM0LHNpemU9MHgxMDAwKQp3cml0ZUJ1ZmZlcihzY3JfYWRkcj0weDM0LCBkc3RfYWRkcj0weDE0MDAwLCBzaXplPTB4MTAwMCkKDVs9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT1dIDEwMCUgKDIxLzIxIHBhZ2VzKQ=="
258 |  }

2022-12-12T08:35:48.810Z daemon INFO 258 |  RESP: {
258 |    "out_stream": "CkRvbmUgaW4gMy4zMzIgc2Vjb25kcwpyZXNldCgpCg=="
258 |  }

2022-12-12T08:35:48.862Z daemon INFO 258 |  RESP: {}
258 STREAM CLOSED


2022-12-12T08:35:49.033Z daemon INFO INFO[0102] from discovery builtin:serial-discovery received message type: remove, port: /dev/cu.usbmodem14301 

2022-12-12T08:35:49.033Z daemon INFO 3 |  RESP: {
3 |    "event_type": "remove",
3 |    "port": {
3 |      "port": {
3 |        "address": "/dev/cu.usbmodem14301",
3 |        "protocol": "serial"
3 |      }
3 |    }
3 |  }

2022-12-12T08:35:49.034Z discovery-log INFO {"eventType":"remove","port":{"matchingBoardsList":[],"port":{"address":"/dev/cu.usbmodem14301","label":"","protocol":"serial","protocolLabel":"","propertiesMap":[]}},"error":""}
2022-12-12T08:35:49.036Z root INFO Attached boards and available ports changed:
2022-12-12T08:35:49.036Z root INFO  - Detached board: Arduino Nano 33 BLE [arduino:mbed_nano:nano33ble] from /dev/cu.usbmodem14301 Serial Port (USB)
2022-12-12T08:35:49.036Z root INFO ------------------------------------------
```

For the record, when this happens no need to reset the board. Starting another `board list watch` process can detect the board, even if the CLI daemon has lost tracking it in IDE2 after the upload:

<img width="1085" alt="Screen Shot 2022-12-12 at 09 51 39" src="https://user-images.githubusercontent.com/1405703/207357564-d4f21a33-c433-4a8f-8efc-44f7889c03c6.png">

Full gRPC log from IDE2:  [nano33ble_is_not_discovered_after_verify_upload.txt](https://github.com/arduino/serial-discovery/files/10218695/nano33ble_is_not_discovered_after_verify_upload.txt)

### To reproduce

 - Start IDE2,
 - Attach the Nano 33 BLE,
 - Upload,
 - Upload and continue uploading until the discovery fails.

https://user-images.githubusercontent.com/1405703/207362146-30dbf093-4d4f-4610-bc12-709e79f4ce24.mp4

I cannot consistently reproduce the bug.

### Expected behavior

 - The discovery can reliably detect the board after the upload.
 - No `from discovery builtin:serial-discovery received message type: start_sync, message: Error enumerating serial ports: Error while enumerating serial ports: Error extracting port info from device: Property not found: IOCalloutDevice ` error in the logs.

### serial-discovery version

1.1.0 or 1.3.2

### Operating system

macOS

### Operating system version

12.5.1

### Additional context

I see this in the daemon logs in IDE2:

```
INFO[0000] Loading package builtin from: /Users/a.kitta/Library/Arduino15/packages/builtin 
INFO[0000] Checking existence of 'tools' path: /Users/a.kitta/Library/Arduino15/packages/builtin/tools 
INFO[0000] Loading tools from dir: /Users/a.kitta/Library/Arduino15/packages/builtin/tools 
INFO[0000] Loaded tool                                   tool="builtin:ctags@5.8-arduino11"
INFO[0000] Loaded tool                                   tool="builtin:mdns-discovery@1.0.6"
INFO[0000] Loaded tool                                   tool="builtin:serial-discovery@1.1.0"
INFO[0000] Loaded tool                                   tool="builtin:serial-discovery@1.3.2"
INFO[0000] Loaded tool                                   tool="builtin:serial-monitor@0.11.0"
```

```
a.kitta@Akoss-MacBook-Pro Desktop % ls -al ~/Library/Arduino15/packages/builtin/tools/serial-discovery
total 0
drwxr-xr-x  4 a.kitta  staff  128 Oct 28 09:19 .
drwxr-xr-x  6 a.kitta  staff  192 Oct  5 14:21 ..
drwxr-xr-x  3 a.kitta  staff   96 Oct 28 09:19 1.1.0
drwxr-xr-x  4 a.kitta  staff  128 Oct  5 14:21 1.3.2
```

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/serial-discovery/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by cmaglie** [comment]
This should be fixed by #52
